### ISSUE TITLE
Container images

### ISSUE THREAD

**Issue by inful** [nsc-norway/covid-seq#3]
Would it be possible for you to provide reference to the docker container images used for generating your singularity images?

**Comment by fa2k** [comment]
I have uploaded our Docker files and a README file that describes how we generate the singularity images.

As you can see, it's a bit of a manual process. I don't recommend running the README as a script, but instead running the commands.

I will close the issue, but feel free to comment and / or re-open it if you have some problems with the container images. Sorry it took so long to reply. We are doing quite a lot of research into finding the optimal pipeline for the Swift data, so you can expect a new version of the pipeline to come quite soon.
