### ISSUE TITLE
samplesheet format

### ISSUE THREAD

**Issue by inful** [nsc-norway/covid-seq#5]
Would it be possible for you to provide an example or a format description of the sampleListFile?

An example with header and one sample line would suffice :)

**Comment by fa2k** [comment]
I have added an example file here:

https://github.com/nsc-norway/covid-seq/blob/main/doc/sampleList.example.csv

And documentation in README.md. But there may be an issue with the project name format (ProjectName column) -- that the report generator requires a specific format of the name. I will check this later, so keeping the issue open for now.

**Comment by inful** [comment]
Thank you very much :)
